pull_request_rules:
- actions:
    review:
      bot_account: mergify-test4
      message: WTF?
      type: REQUEST_CHANGES
  conditions:
  - base=20211221142438/test_review_with_oauth_token/main
  - '#approved-reviews-by>=1'
  name: requested
