pull_request_rules:
- actions:
    label:
      add:
      - unstable
      - foobar
      remove:
      - stable
      - what
  conditions:
  - base=20210910062419/test_label/main
  - label=stable
  name: rename label
