pull_request_rules:
- actions:
    queue:
      name: default
      priority: high
      update_bot_account: mergify-test4
      update_method: rebase
  conditions:
  - base=20220505161156/test_queue_with_rebase_update_method/main
  - label=queue
  name: Merge priority high
queue_rules:
- allow_inplace_checks: true
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  speculative_checks: 5
