pull_request_rules:
- actions:
    merge:
      method: merge
  conditions:
  - base=20220426112710/test_merge_and_closes_issues/main
  - status-success=continuous-integration/fake-ci
  name: Merge on main
