pull_request_rules:
- actions:
    label:
      add:
      - unstable
      - foobar
      - vector
      remove:
      - stable
      - what
  conditions:
  - base=20220116204725/test_label_basic/main
  name: rename label
