pull_request_rules:
- actions:
    merge:
      priority: high
  conditions:
  - base=20211203102340/test_no_strict_mode_brownout/main
  - label=high
  - status-success=continuous-integration/fake-ci
  name: Merge priority high
