pull_request_rules:
- actions:
    delete_head_branch: null
  conditions:
  - base=20210824152713/test_delete_branch/main
  - label=merge
  - merged
  name: delete on merge
- actions:
    delete_head_branch: {}
  conditions:
  - base=20210824152713/test_delete_branch/main
  - label=close
  - closed
  name: delete on close
