pull_request_rules:
- actions:
    queue:
      name: default
      priority: high
  conditions:
  - base=20220511121909/test_queue_just_rebase/main
  - label=queue
  name: Merge priority high
queue_rules:
- allow_inplace_checks: true
  conditions:
  - label=queue
  name: default
  speculative_checks: 5
