pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20211014184717/test_queue_cancel_and_refresh/main
  - label=queue
  name: Tchou tchou
queue_rules:
- conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  speculative_checks: 5
