pull_request_rules:
- actions:
    assign:
      users:
      - mergify-test1
    subscription:
      subscribed:
      - mergify-test2
  conditions:
  - base=20220105163730/test_subscription/main
  name: subscription
