pull_request_rules:
- actions:
    label:
      add:
      - unstable
      - foobar
      - vector
      remove:
      - stable
      - what
      - remove-me
  conditions:
  - base=20220430125758/test_label_basic/main
  name: rename label
