pull_request_rules:
- actions:
    queue:
      name: default
      priority: high
  conditions:
  - base=20211215084803/test_queue_inplace/main
  - check-success=slow-ci
  - label=queue
  name: Merge priority high
queue_rules:
- conditions:
  - check-success=continuous-integration/fake-ci
  name: default
  speculative_checks: 5
