pull_request_rules:
- actions:
    merge:
      strict: smart+ordered
  conditions:
  - base=20220111194912/test_merge_rule_deleted/main
  - status-success=continuous-integration/fake-ci
  name: Merge me
