pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20220511115158/test_queue_cancel_and_refresh/main
  - label=queue
  name: Tchou tchou
queue_rules:
- allow_inplace_checks: true
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  speculative_checks: 5
