pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20220421011506/test_queue_ci_timeout_or_conditions/main
  - check-success=continuous-integration/fake-ci
  name: queue
queue_rules:
- allow_inplace_checks: false
  checks_timeout: 10 m
  conditions:
  - or:
    - check-success=continuous-integration/fake-ci
    - check-success=continuous-integration/other-ci
  name: default
