pull_request_rules:
- actions:
    dismiss_reviews:
      approved: from_requested_reviewers
      'on': always
  conditions:
  - base=20211221190707/test_dismiss_reviews_from_requested_reviewers/main
  name: dismiss reviews
