pull_request_rules:
- actions:
    merge:
      strict: smart+ordered
  conditions:
  - base=20211014183739/test_merge_rule_deleted/main
  - status-success=continuous-integration/fake-ci
  - label=automerge
  name: Merge only if label is present
