pull_request_rules:
- actions:
    review:
      bot_account: I-hope-this-user-will-never-exists-otherwise-this-test-will-start-failing
      type: APPROVE
  conditions:
  - base=20220926044803/test_review_on_closed_pr/main
  name: approve
