pull_request_rules:
- actions:
    dismiss_reviews:
      approved: true
      changes_requested:
      - mergify-test1
  conditions:
  - base=20211012155917/test_dismiss_reviews/main
  name: dismiss reviews
