pull_request_rules:
- actions:
    merge: {}
  conditions:
  - base!=20211110080409/test_change_mergify_yml_in_meantime_on_bug_pull_request/main
  name: nothing
- actions:
    merge: {}
  conditions:
  - label!=wip
  name: foobar
