pull_request_rules:
- actions:
    queue:
      name: default
      priority: high
  conditions:
  - base=20220502144136/test_ongoing_train_second_pr_ready_first/main
  - label=queue
  name: Merge priority high
queue_rules:
- allow_inplace_checks: true
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  speculative_checks: 5
