pull_request_rules:
- actions:
    queue:
      name: default
      priority: high
  conditions:
  - base=20220506202709/test_more_ci_in_pull_request_rules_succeed/main
  - status-success=continuous-integration/fake-ci
  - status-success=very-long-ci
  - label=queue
  name: Merge priority high
queue_rules:
- allow_inplace_checks: true
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  speculative_checks: 5
