pull_request_rules:
- actions:
    merge:
      priority: high
      strict: smart+ordered
  conditions:
  - base=20211007074354/test_strict_mode_brownout/main
  - label=high
  - status-success=continuous-integration/fake-ci
  name: Merge priority high
