pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20220421005205/test_queue_ci_timeout_or_conditions/main
  - check-success=continuous-integration/fake-ci
  name: queue
queue_rules:
- allow_inplace_checks: false
  checks_timeout: 10 m
  conditions:
  - or: !!set
      check-success=continuous-integration/fake-ci: null
      check-success=continuous-integration/other-ci: null
  name: default
