pull_request_rules:
- actions:
    review:
      type: APPROVE
  conditions:
  - base=20221122161232/test_review_normal/main
  name: approve
- actions:
    review:
      message: WTF?
      type: REQUEST_CHANGES
  conditions:
  - base=20221122161232/test_review_normal/main
  - '#approved-reviews-by>=1'
  name: requested
