pull_request_rules:
- actions:
    queue:
      name: default
      priority: high
  conditions:
  - base=20220410064915/test_queue_just_rebase/main
  - label=queue
  name: Merge priority high
queue_rules:
- conditions:
  - label=queue
  name: default
  speculative_checks: 5
