pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20210923142502/test_jit_schedule_no_spec_checks_on_queue_rules/main
  name: fast queue
queue_rules:
- conditions:
  - 'schedule: MON-FRI 08:00-17:00'
  name: default
