pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20210923092449/test_rule_deleted/main
  name: Merge me
queue_rules:
- allow_inplace_speculative_checks: false
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  speculative_checks: 5
