pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20211021185629/test_queued/main
  - label=ready-to-merge
  name: Merge priority high
- actions:
    label:
      add:
      - queued
  conditions:
  - base=20211021185629/test_queued/main
  - queued
  name: Add queued label
- actions:
    label:
      remove:
      - queued
  conditions:
  - base=20211021185629/test_queued/main
  - -queued
  name: Remove queued label
queue_rules:
- conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  speculative_checks: 5
