pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20220316090551/test_queue_ci_timeout/main
  - check-success=continuous-integration/fake-ci
  name: queue
queue_rules:
- checks_timeout: 10 m
  conditions:
  - check-success=continuous-integration/fake-ci
  name: default
  speculative_checks: 2
