pull_request_rules:
- actions:
    queue:
      branch_protection_required_for_queueing: false
      method: squash
      name: default
  conditions:
  - base=20211025121326/test_queue_without_branch_protection_for_queueing/main
  - label=queue
  name: Merge priority high
queue_rules:
- conditions: []
  name: default
