pull_request_rules:
- actions:
    merge:
      method: merge
  conditions:
  - base=20220407095757/test_merge_custom_msg_merge/main
  - status-success=continuous-integration/fake-ci
  name: Merge on main
