pull_request_rules:
- actions:
    assign:
      users:
      - mergify-test1
    subscription:
      subscribed:
      - mergify-test1
  conditions:
  - base=20220105163259/test_subscription/main
  name: subscription
