pull_request_rules:
- actions:
    review:
      bot_account: '{{ body }}'
      type: APPROVE
  conditions:
  - base=20211221141940/test_review_with_oauth_token/main
  name: approve
- actions:
    review:
      bot_account: mergify-test4
      message: WTF?
      type: REQUEST_CHANGES
  conditions:
  - base=20211221141940/test_review_with_oauth_token/main
  - '#approved-reviews-by>=1'
  name: requested
