pull_request_rules:
- actions:
    queue:
      commit_message: title+body
      priority: high
  conditions:
  - base=20220114145842/test_commit_message_queue_brownout/main
  - label=high
  - status-success=continuous-integration/fake-ci
  name: Merge priority high
