pull_request_rules:
- actions:
    queue:
      name: default
      priority: high
  conditions:
  - base=20220511121948/test_queue_manual_merge/main
  - label=queue
  name: Merge priority high
queue_rules:
- allow_inplace_checks: true
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  speculative_checks: 5
