pull_request_rules:
- actions:
    queue:
      method: squash
      name: default
  conditions:
  - base=20211207075713/test_queue_without_queue_conditions/main
  - check-status=continuous-integration/fake-ci
  name: Merge priority high
queue_rules:
- conditions: []
  name: default
