pull_request_rules:
- actions:
    assign:
      users:
      - mergify-test1
    subscription:
      subscribed:
      - mergify-test3
  conditions:
  - base=20220105163811/test_subscription/main
  name: subscription
