pull_request_rules:
- actions:
    label:
      add:
      - foobar
    subscription:
      subscribed:
      - mergify-test4
  conditions:
  - base=20220105170606/test_subscription/main
  name: subscription
