pull_request_rules:
- actions:
    dismiss_reviews:
      approved: true
      changes_requested:
      - mergify-test1
      message: '{{Loser}}'
  conditions:
  - base=20220411160704/test_dismiss_reviews_custom_message_attribute_error/main
  name: dismiss reviews
