pull_request_rules:
- actions:
    request_reviews:
      random_count: 2
      users_from_teams:
      - bot
  conditions:
  - base=20210930071857/test_request_reviews_users_from_teams/main
  name: request_reviews
