pull_request_rules:
- actions:
    comment:
      message: and or pr
  conditions:
  - or:
    - and:
      - base=20220502073606/test_and_or/main
      - closed
      - label=foo
    - merged
  name: no-draft
