pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20220107143654/test_queue_inplace_interrupted/main
  name: Merge priority high
queue_rules:
- conditions: []
  name: default
