pull_request_rules:
- actions:
    queue:
      name: default
      priority: high
  conditions:
  - base=20211022063701/test_merge_queue_refresh/main
  - label=queue
  name: Merge priority high
queue_rules:
- conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  speculative_checks: 5
