pull_request_rules:
- actions:
    queue:
      name: default
      priority: high
  conditions:
  - base=20210930053122/test_queue_with_branch_protections/main
  name: Merge priority high
queue_rules:
- conditions: []
  name: default
  speculative_checks: 5
