pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20220411190611/test_unqueue/main
  name: Queue
queue_rules:
- conditions:
  - status-success=continuous-integration/fake-ci
  name: default
