pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20211209143059/test_queue_ci_timeout/main
  name: queue
queue_rules:
- ci_timeout: 1s
  conditions:
  - ckeck-success=continuous-integration/fake-ci
  name: default
