pull_request_rules:
- actions:
    merge:
      commit_message_template: '{{ title }} (#{{ number }})


        {{body}}

        '
  conditions:
  - base=20220325151844/test_merge_template_with_empty_body/main
  name: merge on main
